import { StyleSheet } from "react-native";

const GlobalStyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    alignContent: "center",
    justifyContent: "space-between",
    padding: 20,
    backgroundColor: "#ffffff",
  },
  textPrimary: {
    fontSize: 18,
    color: "#020103",
    fontFamily: "Comfortaa",
    alignItems: "center",
    justifyContent: "center",
  },
  textSecondary: {
    fontSize: 16,
    color: "#020103",
    fontFamily: "Comfortaa",
    alignItems: "center",
    justifyContent: "center",
  },
  textInfo: {
    fontSize: 12,
    color: "#020103",
    fontFamily: "Comfortaa",
    alignItems: "center",
    justifyContent: "center",
  },
  textPlaceholder: {
    fontSize: 12,
    color: "#D8B8F1",
    fontFamily: "Comfortaa",
  },
  headerText: {
    fontSize: 24,
    fontWeight: 600,
    fontFamily: "Michroma",
    color: "#020103",
    alignItems: "center",
    justifyContent: "center",
  },
  subHeaderText: {
    fontSize: 20,
    fontWeight: 300,
    fontFamily: "Comfortaa",
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButton: {
    backgroundColor: "#9D4EDD",
    color: "#ffffff",
    height: 50,
    minWidth: "90%",
    padding: 12,
    marginBottom: 12,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButton: {
    backgroundColor: "#D8B8F1",
    color: "#020103",
    height: 50,
    minWidth: "90%",
    padding: 12,
    marginBottom: 12,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  ghostButton: {
    backgroundColor: "transparent",
    color: "#020103",
    height: 50,
    minWidth: "90%",
    padding: 12,
    borderRadius: 16,
    borderColor: "#020103",
    alignItems: "center",
    justifyContent: "center",
  },
  formInput: {
    backgroundColor: "transparent",
    height: 50,
    minWidth: "80%",
    padding: 12,
    borderBottomColor: "#020103",
    borderBottomWidth: 1,
    alignItems: "center",
    justifyContent: "space-between",
  },
  searchInput: {
    backgroundColor: "#E2CAF5",
    color: "#020103",
    height: 50,
    width: "90%",
    padding: 12,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  pillTabs: {
    backgroundColor: "#D8B8F1",
    borderColor: "#020103",
    color: "#020103",
    height: 50,
    width: "100%",
    padding: 12,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  badges: {
    backgroundColor: "#120919",
    color: "#ffffff",
    height: 50,
    width: "100%",
    padding: 12,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  spacerLarge: {
    marginBottom: 32,
  },
  spacerMed: {
    marginBottom: 24,
  },
  spacerSmall: {
    marginBottom: 16,
  },
  spacerSmaller: {
    marginBottom: 12,
  },
  spacerXSmall: {
    marginBottom: 8,
  },
});

export default GlobalStyles;
