import { StyleSheet } from "react-native";

const GlobalStyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    alignContent: "center",
    justifyContent: "space-between",
    padding: 20,
    backgroundColor: "#ffffff",
  },
  textPrimary: {
    fontSize: 16,
    color: "#250206",
    fontFamily: "Comfortaa",
    alignItems: "center",
    justifyContent: "center",
  },
  textSecondary: {
    fontSize: 14,
    color: "#250206",
    fontFamily: "Comfortaa",
    alignItems: "center",
    justifyContent: "center",
  },
  textInfo: {
    fontSize: 12,
    color: "#250206",
    fontFamily: "Comfortaa",
    alignItems: "center",
    justifyContent: "center",
  },
  textPlaceholder: {
    fontSize: 12,
    color: "#F45B69",
    fontFamily: "Comfortaa",
  },
  headerText: {
    fontSize: 24,
    fontFamily: "Michroma_400Regular",
    color: "#020103",
    alignItems: "center",
    justifyContent: "center",
  },
  subHeaderText: {
    fontSize: 20,
    fontWeight: 300,
    fontFamily: "Comfortaa",
    alignItems: "center",
    justifyContent: "center",
  },
  primaryButton: {
    backgroundColor: "#F45B69",
    color: "#ffffff",
    height: 50,
    minWidth: "90%",
    padding: 12,
    marginBottom: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  secondaryButton: {
    backgroundColor: "#F89DA5",
    color: "#030000",
    height: 50,
    minWidth: "90%",
    padding: 12,
    marginBottom: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  TertiaryButton: {
    backgroundColor: "transparent",
    color: "#030000",
    borderWidth: 1,
    borderColor: "#030000",
    height: 50,
    minWidth: "90%",
    padding: 12,
    marginBottom: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },

  ghostButton: {
    backgroundColor: "transparent",
    color: "#030000",
    height: 50,
    minWidth: "90%",
    padding: 12,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  formInput: {
    backgroundColor: "transparent",
    height: 50,
    minWidth: "80%",
    padding: 12,
    marginBottom: 6,
    borderBottomColor: "#030000",
    borderBottomWidth: 1,
    alignItems: "center",
    justifyContent: "space-between",
  },
  searchInput: {
    backgroundColor: "#FDDEE1",
    color: "#030000",
    height: 50,
    width: "90%",
    padding: 12,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  pillTabs: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#FBBDC3",
    color: "#030000",
    height: 40,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 99999,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  badges: {
    backgroundColor: "#F67C87",
    color: "#78262E",
    height: 50,
    width: "100%",
    padding: 12,
    borderRadius: 999,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  spacerLarge: {
    marginBottom: 32,
  },
  spacerMed: {
    marginBottom: 24,
  },
  spacerSmall: {
    marginBottom: 16,
  },
  spacerSmaller: {
    marginBottom: 12,
  },
  spacerXSmall: {
    marginBottom: 8,
  },
});

export default GlobalStyles;
